version: '3'
services:
  server:
    image: "ghcr.io/angelsflyinhell/place_ts_server:latest"
    container_name: place_server
    restart: always
    network_mode: host
    environment:
      MONGO_URI: mongodb://your:mongo@uri:27017/place
      PORT: 9000
  web:
    image: "ghcr.io/angelsflyinhell/place_client:latest"
    container_name: place_client
    restart: always
    ports:
      - "9001:80"
  