name: check:client

on:
  push:
    branches: [ "main" ]
    paths:
      - 'www/**'

defaults:
  run:
    working-directory: www

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache-dependency-path: www/package-lock.json
    - run: yarn install
    - run: yarn build --if-present