name: Deploy TS Server Image

on:
  workflow_run:
    workflows: ["check:ts-server"]
    types:
      - completed

jobs:
  build:
    name: Deployment
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - uses: actions/checkout@v3
    - name: Build and push the Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: place_ts_server
        tags: latest
        dockerfile: 'ts-server/Dockerfile'
        directory: 'ts-server'
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}